### ISSUE TITLE
License says "all rights reserved" which isn't open source

### ISSUE THREAD

**Issue by thedrow** [vaidik/sherlock#11]
Are we allowed to use this package? Is it only published for educational purposes?
If not, please choose an open source license.

**Comment by vaidik** [comment]
Apologies for responding to this issue so late. If this blocked any of your work or made it impossible for you to use this library, then I apologize for that.

I had actually put that copyright file without even doing the least of research to understand what it means and just put it there as I saw a similar file in another project's repo. Your issue actually made me go ahead and read about it.

This project exists in public domain. It is open source and it is for everyone to use. I have removed the copyright and have added a TLDR in the License section in README.

**Comment by vaidik** [comment]
Thanks once again for pointing this out and making sure that this project is legally correct.

**Comment by thedrow** [comment]
Thanks!

**Comment by thedrow** [comment]
MIT license != public domain.
MIT does provide some sensible requirements. Public domain means that the users are not required to do anything.
